### ISSUE TITLE
URL path rewriting at M4d

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-5gms-application-server#10]
**Feature description**
Rewriting the request URL paths of media resource requests handled by the 5GMSd AS.

**Relevant specifications and corresponding sections**
[26.501 - 5G Media Streaming (5GMS); General description and architecture (Release 17)](https://www.3gpp.org/ftp/Specs/archive/26_series/26.501)
[26.512 - 5G Media Streaming (5GMS); Protocols (Release 17)](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512)

**Comment by davidjwbbc** [comment]
Initial implementation is very basic and requires some extra checking of the validity of the given regex.

**Comment by davidjwbbc** [comment]
TS 26.512 table 7.6.3.1-1 states that the regular expression used in the `pathRewriteRule.request_pattern` follows ECMA-262 (v5.1) syntax. nginx uses Perl regular expressions. From what I can see from the ECMA-262 regular expression grammar and perlre man pages, ECMA RegExp regular expressions appear to be a direct subset of Perl regular expressions.

The PyPi "regex" package contains the regex Python module which provides a Perl regular expression implementation. Therefore I have used this module to implement a validation of the request_pattern input and to assist in adding extra parts to the regular expression and replacement string to handle the URL rewriting for nginx.
