### ISSUE TITLE
Translate ContentHostingConfiguration to nginx configuration

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-5gms-application-server#13]
# Feature description
Translates JSON Content Hosting Configuration into file format of chosen web server. The configured M4d endpoint should then be presented by the web server/proxy.

## GanttLab
GanttStart: 2022-09-19
GanttDue: 2022-10-10

**Comment by davidjwbbc** [comment]
nginx Web Proxy class in the current implementation provides this feature.
