### ISSUE TITLE
5GMS Application Server: Core Development Plan & Questions

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-5gms-application-server#2]
This issue is supposed to be used to discuss and answer the following questions

* Which programming language do we want to use to implement the AS
* What would be the MVP?
* Which web server should we use?
  * Apache
  * Nginx
  * Varnish
  * node.js express

## GanttLab
GanttStart: 2022-08-31
GanttDue: 2022-09-19

**Comment by davidjwbbc** [comment]
The proposal for MVP#1 is to use a Python application which will read in a ContentHostingConfiguration (defined in TS 26.512 M1 ContentHostingProvisioning) in JSON format to determine the configuration, configure the web server and start it. We will start with nginx as the web server, but build the Python application in a way which will make it easy to add management of other web servers.

**Comment by rjb1000** [comment]
The key decisions are documented above.
