### ISSUE TITLE
Improve life-cycle management of web proxy server

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-5gms-application-server#3]
# Feature description
Extending #14, maintain a watchdog to restart it after a crash or if the configuration changes.

# Relevant specifications and corresponding sections
See #1 

## GanttLab
GanttStart: 2022-09-19
GanttDue: 2022-09-26

**Comment by davidjwbbc** [comment]
Have implemented process restarting logic (failure in event of rapid restarts). Have yet to implement the configuration reloading logic. This could be done either as:

- Reload the configuration and ContentHostingConfiguration, restart nginx.
- Reload the configuration and ContentHostingConfiguration if they've changed, restart nginx if any changes.
- Reload the configuration and ContentHostingConfiguration if they've changed, restart nginx if changes affect the nginx configuration.
- Reload the configuration and ContentHostingConfiguration if they've changed, choose restart of reload of nginx dependant on what has changed in nginx configuration.

**Comment by rjb1000** [comment]
As for the mechanism used the restart nginx: there is a brute force restart that unceremoniously terminates existing client connections and a graceful restart that hands over to a new process.

For the purposes of MVP#1, the brute force restart is good enough. We may revisit this later to make it more graceful.
