### ISSUE TITLE
Implement M3 test client

### ISSUE THREAD

**Issue by rjb1000** [5G-MAG/rt-5gms-application-server#31]
# Feature description
Using OpenAPI YAML interface definition files, implement an M3 test client for the M3 server developed in #30.
* Provision and manage Server Certificate resources available to the test client as local X.509 PEM files.
  * Create, Retrieve, Update, Destroy.
* Provision and manage Content Hosting Configuration resources available to the test client as local JSON files.
  * Create, Retrieve, Update, Destroy.
  * Purge the associated content cache.

# Relevant specifications and corresponding sections
TS 26.512 plus pre-standardisation M3 Open API YAML interface definition files.

# Additional context
This test client effectively replaces the need for the 5GMS AS to load its Content Hosting Configuration from a local file.

The test client allows multiple Content Hosting Configurations to be provisioned and managed.

It may be advantageous to develop the M3 test client in C so that some of the code can be reused as part of the M3 client in the 5GMSd AF - see 5G-MAG/rt-5gms-application-function#7.

**Comment by davidjwbbc** [comment]
Implemented a basic client which can do certificates list/add/update/delete and content hosting configuration list/add/update/delete. Code needs tidying up and M3 operations separating into a module, away from command line parsing, for re-use in unit tests.

**Comment by davidjwbbc** [comment]
Code tidied up and pushed to the feature-add-m3-interface branch on my fork.

**Comment by davidjwbbc** [comment]
httpx works very well. To do HTTP/1.1 with HTTP/2 upgrade you can use:
```python
client = httpx.AsyncClient(http1=True, http2=True, headers={'Connection': 'upgrade', 'Upgrade': 'h2c})
```
...and for HTTP/2 prior knowledge:
```python
client = httpx.AsyncClient(http1=False, http2=True)
```

I've set the test client to prior knowledge to match the other 3GPP NF interfaces.

**Comment by davidjwbbc** [comment]
Added the cache purge operation to the test client. This can take two forms:
`m3_client_cli.py -H <host>:<port> purge <provisioning-session-id>` - This will purge all cache entries for the provisioning session (`pattern` field in the request body is not present).
`m3_client_cli.py -H <host>:<port> purge <provisioning-session-id> <regex>` - This will purge all cache entries for the provisioning session where the cached URL path matches the regex (sent in the `pattern` field of the request body), the URL path used for the comparison is the full path of the object on the backend origin.
