### ISSUE TITLE
Use OpenAPI to bindings script from 5G-MAG/rt-common-shared repository.

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/rt-5gms-application-server#34]
## Enhancement
This project has a script at `build_scripts/generate_openapi` which is used to generate the python bindings from the 5G APIs OpenAPI YAML.

Once PR #33 has been merged, there will be a more generic version of this script at `docs/rt-common-shared/5gms/scripts/generate_openapi`.

When this script is available the `build_scripts/generate_openapi` should be modified to call the more generic script, from rt-common-shared, with appropriate parameters to build the bindings.

## Requirements
PR #33 will need to be merged before this can be done.

**Comment by rjb1000** [comment]
Seems a bit unintuitive to import the submodule under `docs`, @davidjwbbc.

**Comment by davidjwbbc** [comment]
The location is due to the rt-common-shared submodule only having example files which were moved from the docs directory in this repository to rt-common-shared. So preserving the examples under docs seemed sensible. The rt-common-shared submodule now contains the helper scripts too, whiich means the location of this submodule should probably move out of the docs directory.

I would suggest:
1. Move `docs/rt-common-shared` to `external/rt-commonm-shared`
2. Modify `pyproject.toml` to distribute the examples from `external/rt-common-shared/5gms/examples/*` with the other docs.
3. Add `external/rt-common-shared` as a recursive include in the `MANIFEST.in`
4. Make `build_scripts/generate_openapi` use the common script from `external/rt-common-shared/5gms/scripts/generate_openapi`.
5. Rename `build_scripts/generate_openapi` to `build_scripts/generate_5gms_as_openapi` to avoid confusion between the two scripts.
6. Modify `build_scripts/backend.py` to use the renamed script.

**Comment by rjb1000** [comment]
Sounds like a good plan, @davidjwbbc.
