### ISSUE TITLE
MVP#1 Application Server installation issues/observations

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-5gms-application-server#39]
This ticket is meant to collect issues and observations that occurred during the installation of the Application Server

### Missing module
Following the installation guide I ran into the following error when running `5gms-application-server -h`:

````
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/5gms-application-server", line 5, in <module>
    from rt_5gms_as.app import main
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rt_5gms_as/app.py", line 32, in <module>
    from .context import Context
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rt_5gms_as/context.py", line 34, in <module>
    from .openapi_5g.model.content_hosting_configuration import ContentHostingConfiguration
ModuleNotFoundError: No module named 'rt_5gms_as.openapi_5g'
````

### Missing folders
Strictly following the installation guide I ran into a problem of missing folders. The following commands are required to create the folders:
```` 
mkdir /var/cache/rt-5gms
mkdir /var/log/rt-5gms
mkdir /run/rt-5gms
```` 

### Nginx port bindings
Binding to port `80` is only possible with root privileges. Running `5gms-application-server external/rt-common-shared/5gms/examples/ContentHostingConfiguration_Big-Buck-Bunny_pull-ingest.json` lead to a `nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)` error.

This can be solved by following the instructions in the [development documentation](https://github.com/5G-MAG/rt-5gms-application-server/blob/main/docs/README.md) and creating an adjusted configuration using other ports:
```` 
[DEFAULT]
log_dir = /tmp/rt-5gms-as/logs
run_dir = /tmp/rt-5gms-as

### 5GMS Application Server specific configurations
[5gms_as]
cache_dir = /tmp/rt-5gms-as/cache
http_port = 8080
https_port = 8443

### 5GMS Application Server nginx specific configuration
[5gms_as.nginx]
root_temp = /tmp/rt-5gms-as
```` 

The new config can be provided via `5gms-application-server -c custom-application-server.conf external/rt-common-shared/5gms/examples/ContentHostingConfiguration_Big-Buck-Bunny_pull-ingest.json`

Afterwards the sample MPD is available at `http://localhost:8080/m4d/provisioning-session-d54a1fcc-d411-4e32-807b-2c60dbaeaf5f/BigBuckBunny_4s_onDemand_2014_05_09.mpd`

**Comment by davidjwbbc** [comment]
The missing module is odd, it looks like the OpenAPI bindings were not created.

The build backend collects a dependencies list before it creates the distribution tar file. I suspect the `build_scripts/backend.py` may need to intercept the call to find the dependencies in the build backend and build the `src/rt_5gms_as/openapi_5g` directory before passing the call onto the setuptools backend. It already does this for the sdist command (to create the distribution tar), but maybe it needs to perform the action a little earlier in the build process.

I'll do some investigating and see if what I suspect is true.

**Comment by davidjwbbc** [comment]
The application server should create any missing folders it sees from its configuration. But obviously can't if it doesn't have permission to do so. The defaults are set assuming the script will be run as root for a proper system service. Using an alternative configuration pointing to directories that the user can create/modify allows this to be run as an unprivileged user.

**Comment by jordijoangimenez** [comment]
"generate_openapi" should be renamed to "generate_5gms_as_openapi" in section "Running the example without building" of /docs/rREADME.md

**Comment by jordijoangimenez** [comment]
In the last step to run the example, I obtain a "ModuleNotFoundError: No module named 'regex'". It may be related to a problem finding the path but I'm not sure at the moment how to fix it

**Comment by jordijoangimenez** [comment]
David, thank you for checking. Actually I could finally fixed it with `sudo apt -y install python3-regex`
regarding the 3 vs 3.8 I checked that it doesn't seem to make a difference and it is all executed correctly from the 3.8 folder.

**Comment by rjb1000** [comment]
With the exception of the MacOS report, I think all problems have been solved, so now it's just a case of updating documentation, right, @davidjwbbc?

**Comment by rjb1000** [comment]
Anything more to be done on this issue @davidjwbbc?

Can we link it to documentation update PR(s) before closing?

**Comment by jordijoangimenez** [comment]
I'm trying to redo the rt-5gms-application-server from scratch to check the development branch. I'm getting:
```
~/rt-5gms-application-server/build_scripts/generate_5gms_as_openapi
/home/fivegmag/rt-5gms-application-server/build_scripts/generate_5gms_as_openapi: 33: Bad substitution
```

**Comment by jordijoangimenez** [comment]
> I'm trying to redo the rt-5gms-application-server from scratch to check the development branch. I'm getting "bad substitution" after Regenerating the 5G API bindings
> 
> ```
> ~/rt-5gms-application-server/build_scripts/generate_5gms_as_openapi
> /home/fivegmag/rt-5gms-application-server/build_scripts/generate_5gms_as_openapi: 33: Bad substitution
> ```

I used "#! /bin/bash" instead of "#! /bin/sh" and it run

**Comment by jordijoangimenez** [comment]
I'm stuck with (apparently) the Nginx configurations. 
On the sites-enabled or sites-available I can only see default. Default comes with port 80.
This seems to be always active, as when trying to launch the rt_5gms_as.app there is a conflict that says address already in use. I'm wondering when is any other configuration used to change ports.

If I manually change the port of the nginx default to 8080 and do systemctl restart nginx, then I can run rt_5gms_as.app
If I then launch the m3_client_cli.py I get:
INFO:rt-5gms-as:Adding content hosting configuration ps1...
INFO:rt-5gms-as:Reloading proxy daemon...
but no success! message. I'm also unable to retrieve the mpd nor the video from neither port 80 nor 8080

**Comment by jordijoangimenez** [comment]
After a while I got a success.
```
fivegmag@fivegmag-NUC8i7HVK:~/rt-5gms-application-server$ tests/m3_client_cli.py -H localhost:7777 add ps1 external/rt-common-shared/5gms/examples/ContentHostingConfiguration_Big-Buck-Bunny_pull-ingest.json
Success!
```

**Comment by davidjwbbc** [comment]
> I'm stuck with (apparently) the Nginx configurations. On the sites-enabled or sites-available I can only see default. Default comes with port 80. This seems to be always active, as when trying to launch the rt_5gms_as.app there is a conflict that says address already in use. I'm wondering when is any other configuration used to change ports.

By default the 5GMS Application server will try to use port 80 for HTTP and port 443 for HTTPS. If you have the nginx service running, it too will use port 80 or 443 by default. Therefore one of these will need to move and personally, since the 5GMS Application Server is under test I'd change that one.

The 5GMS Application Server default ports can be can be easily changed by setting the appropriate values in the configuration file, for example:
```ini
[5gms_as]
http_port = 8080
https_port = 8443
```

These can either be set in the default configuration file (`/etc/rt-5gms/application-server.conf` or `~/.rt-5gms/application-server.conf`) or you can put them in a separate file and use the `-c` command line option to use a different configuration file. Personally I have the following in `local-dev.conf`:
```ini
### Defaults for the 5G-MAG Reference Tools: 5GMS applications
[DEFAULT]
log_dir = /tmp/rt-5gms-as/logs
run_dir = /tmp/rt-5gms-as

### 5GMS Application Server specific configurations
[5gms_as]
log_level = debug
cache_dir = /tmp/rt-5gms-as/cache
certificates_cache = /tmp/rt-5gms-as/certificates
http_port = 8080
https_port = 8443
#access_log = %(log_dir)s/application-server-access.log
#error_log = %(log_dir)s/application-server-error.log
#pid_path = %(run_dir)s/application-server.pid

### 5GMS Application Server nginx specific configuration
[5gms_as.nginx]
#root_temp = /var/cache/rt-5gms/as
root_temp = /tmp/rt-5gms-as
#client_body_temp = %(root_temp)s/client-body-tmp
#proxy_temp = %(root_temp)s/proxy-tmp
#fastcgi_temp = %(root_temp)s/fastcgi-tmp
#uwsgi_temp = %(root_temp)s/uwsgi-tmp
#scgi_temp = %(root_temp)s/scgi-tmp
#pid_path = %(root_temp)s/5gms-as-nginx.pid
```
...and use `venv/bin/5gms-application-server -c local-dev.conf` to run the application server while testing. This redirects all logs and caches to /tmp and runs the application using ports 8080 and 8443.

> 
> If I manually change the port of the nginx default to 8080 and do systemctl restart nginx, then I can run rt_5gms_as.app If I then launch the m3_client_cli.py I get:
> ```
> INFO:rt-5gms-as:Adding content hosting configuration ps1...
> INFO:rt-5gms-as:Reloading proxy daemon...
> ```
> but no success! message. I'm also unable to retrieve the mpd nor the video from neither port 80 nor 8080

That is strange, as though it got part way through deploying, but never replied to the M3 client. It's difficult to know what's going on there, I've not seen that before.

**Comment by jordijoangimenez** [comment]
I've checked the entire AS instructions. All seems to work subject to:
- using "#! /bin/bash" instead of "#! /bin/sh" at ~/rt-5gms-application-server/build_scripts/generate_5gms_as_openapi
- installing a few dependencies I've listed on my development branch: https://github.com/jordijoangimenez/rt-5gms-application-server/blob/development/docs/README.md
- and using -nodes insted of -noenc when using OpenSSL v1.1.1s
I'd like to check all again.

**Comment by davidjwbbc** [comment]
I've got a fix pending for the first one of those.

The second is a documentation update, however most of those should automatically get installed when you do `python3 -m pip install .` as they're listed dependencies in the `pyproject.toml` file. The only prerequisites are up to date `pip`, `setuptools` and `build` modules, the rest should be automatic.

The `-nodes` option is an older (now deprecated) version of the `-noenc` option, I'll take a look at the script to make self signed certificates and see if I can make it pick the right one depending on your local installed version of openssl. This should be a relatively easy fix.

**Comment by jordijoangimenez** [comment]
David,
I think it is very good to have the dependencies in the install. In that case we should remove the installation of those from the documentation.
The -nodes comes because in Ubuntu 20.04 the OpenSSL version is 1.1.1f and I was able to update to 1.1.1s. Not to 3.0 though. What you propose, making this able to pick the right option, would be ideal.

**Comment by jordijoangimenez** [comment]
This has been solved by:
- trying `python3 -m pip install --upgrade pip build setuptools`
- then delete `src/rt_5gms_application_server.egg-info` before doing the `python3 -m pip install .` (as it may contain bad package metadata from the previous build with the old setuptools)
- The installation may warn about the need to update the PATH:
```
WARNING: The script 5gms-application-server is installed in '/home/fivegmag/.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

**Comment by jordijoangimenez** [comment]
I'm testing AF and AS. I've deleted all repos and re-started from scratch. The AF is up and running. When trying to run the AS after having installed it I got:
```
fivegmag@NUC1:~/rt-5gms-application-server$ 5gms-application-server 
Traceback (most recent call last):
  File "/home/fivegmag/.local/bin/5gms-application-server", line 8, in <module>
    sys.exit(main())
  File "/home/fivegmag/.local/lib/python3.10/site-packages/rt_5gms_as/app.py", line 257, in main
    context = Context(config)
  File "/home/fivegmag/.local/lib/python3.10/site-packages/rt_5gms_as/context.py", line 87, in __init__
    self.__loadConfiguration(force=True)
  File "/home/fivegmag/.local/lib/python3.10/site-packages/rt_5gms_as/context.py", line 374, in __loadConfiguration
    os.makedirs(directory)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/run/rt-5gms'
```

**Comment by rjb1000** [comment]
> I'm testing AF and AS. I've deleted all repos and re-started from scratch.

Which branch have you been testing, @jordijoangimenez? I notice this issue is related to *MVP#1*, and I would be surprised if you weren't testing at least v1.0.1, which realises *MVP#2*. Maybe you need to start a new issue and move your latest comments to that?

**Comment by jordijoangimenez** [comment]
I've opened a new issue related to the MVP#2 testing (which Im doing with AS "development" and AF "1.0.1-rc"). The error I'm getting is happening always. I've just launched `5gms-application-server -c ../tests/examples/ContentHostingConfiguration_Big-Buck-Bunny_pull-ingest.json` and I obtain the same issue
