### ISSUE TITLE
Error, following the build instructions 

### ISSUE THREAD

**Issue by tlohmar** [5G-MAG/rt-5gms-application-server#43]
**Describe the bug**

Executing "python3 -m build --sdist" as described in the build instructions (https://github.com/5G-MAG/rt-5gms-application-server#building-a-python-distribution) fails with error: "/usr/bin/python3: No module named build".

OS: Ubuntu 20.04.5 LTS

**Comment by dsilhavy** [comment]
@tlohmar I think I also saw this once, can you please try running this before: `pip install build`

**Comment by davidjwbbc** [comment]
You need the _pip_, _build_ and _setuptools_ Python modules present on your system in order to produce an sdist tar file or to install the application server locally. Looks like this needs to be made clear in the instructions in the README.

**Comment by tlohmar** [comment]
ok, 'build' was missing.  I also needed to add 'apt install python3.8-venv'.

**Comment by jordijoangimenez** [comment]
I suggest we add to the documentation how to install the dependencies. This was done here: https://github.com/5G-MAG/Documentation-and-Architecture/wiki/MBMS-Modem
See step 1.

If we dont want to include the commands, a link to another place where to find the commands would be also useful. I'm going to open a similar issue under the 5GMS-AF

**Comment by jordijoangimenez** [comment]
This should be resolved with the new documentation.
