### ISSUE TITLE
Caching of media content

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-5gms-application-server#5]
**Feature description**
As defined in 26.501: Reduce the need to ingest the same content repeatedly at reference point M2d

**Relevant specifications and corresponding sections**
[26.501 - 5G Media Streaming (5GMS); General description and architecture (Release 17)](https://www.3gpp.org/ftp/Specs/archive/26_series/26.501)
[26.512 - 5G Media Streaming (5GMS); Protocols (Release 17)](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512)

**Comment by rjb1000** [comment]
@davidjwbbc suggests adding a separate 5GMS AS configuration file to describe:
* HTTP daemon listening port number at reference point M4d (and, later, M4u).
* Cache directory.
* Temporary directories.
* Number of child processes.
* etc.

Idea is to define a generic configuration file (e.g. a Python "ini" file) with generic configuration parameters in a "common" section, and parameters specific to a particular HTTP proxy in their own sections.

A template configuration file will be checked in to demonstrate the default values.
