### ISSUE TITLE
Documentation updates after review on 23 Jan 2023

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/rt-5gms-application-server#54]
After testing the latest development branch, @jordijoangimenez, has suggested a couple of improvements to the documentation:
1. [Recommend the need to do `python3 -m pip install --upgrade pip build setuptools` before `python3 -m pip install .`](https://5g-mag.slack.com/archives/C040M6YUB5Y/p1674488598270949)
1. [mention the need to update `$PATH` after having installed 5gms-application-server](https://5g-mag.slack.com/archives/C040M6YUB5Y/p1674488638484329) (as an unprivileged user).
1. Make it clearer in `docs/README.md` how to "Install both the 5GMS Application Server and Application Function".
1. Add example command lines for "Start the Application Server" and "Start the Application Function".

**Comment by jordijoangimenez** [comment]
Regarding /docs/README.md

I would like that we make a bit more clear how to execute the following:

> Install both the 5GMS Application Server and Application Function. 
(I would add links to the installation pages... perhaps trivial though).

...
> Start the Application Server.

(5g-ms-application-server ... let's add an example)

> Start the Application Function.

(/install/bin/open5gs-msafd -c msaf.yaml ... let's add an example)

**Comment by davidjwbbc** [comment]
**For number 1**
This is an issue if older versions of the `pip` `build` and/or `setuptools` Python modules are already installed on the system. Although the documentation isn't clear, it appears that the `--upgrade` flag does not require that the module be already installed. When present will upgrade the specified modules if they already installed. Without the flag, if a module is already installed it is left at the current version instead of being updated. Therefore changing the current instructions to include the upgrade flag should fix some issues with pip, build and setuptools version mismatches.

**For number 2**
- If the pip install command is run as the admin user (`root`) then it would install the application on normal paths, not requiring an update to `$PATH`.
- If the pip install command is run in a Python venv (e.g. `venv/bin/python3 -m pip install .`), then the command is installed in the venv bin directory and will be on the `$PATH` if the venv enviroment has been activated (e.g. `source venv/bin/activate`), or can be run directly from the bin directory, e.g.`venv/bin/5gms-application-server`.
- If the pip install command is run by an unprivileged user then the application server will be installed in their local home directory, a warning is displayed about updating `$PATH` to include this directory. Alternatively the command can be run by specifying the full path, e.g. `~/.local/bin/5gms-application-server`.

**Comment by jordijoangimenez** [comment]
Another thing...
At the AS, we got the examples under tests/examples
At the AF they are under just /examples

Would it make sense to push the examples to another repo so they are just in one place and updated only once? e.g. at the rt-common-shared or at the rt-mbms-examples (repurposing the name to rt-examples, it's also weird that rt-mbms-examples contains flute but that's for another moment...)

**Comment by davidjwbbc** [comment]
> Another thing... At the AS we've got the examples under tests/examples At the AF they are under just /examples
> 
> Would it make sense to push the examples to another repo so they are just in one place and updated only once? e.g. at the rt-common-shared or at the rt-mbms-examples (repurposing the name to rt-examples, it's also weird that rt-mbms-examples contains flute but that's for another moment...)

They were moved out of rt-common-shared because, although similar, the examples for the Application Server are different from the ones for the Application Function.

For the Application Server they are only needed if you are doing stand alone testing on the Application Server without the Application Function, which is why they are in `tests/examples` near the m3 test client script.

For the Application Function they are example configurations and were put in `examples`. Might be better renaming that directory to `example-configurations`.
