### ISSUE TITLE
5gms-application-server reports `Path parameters cannot have a default value`

### ISSUE THREAD

**Issue by WingPig99** [5G-MAG/rt-5gms-application-server#66]
**Describe the bug**
I compiled the `5gms-application-server` on release `rt-5gms-application-server-1.1.0` following the guild on Arch Linux. Every went fine until running `5gms-application-server`. It reports `Path parameters cannot have a default value`. Any idea about this?

**To Reproduce**
1. `5gms-application-server -h`

**Expected behavior**
Print out the help info.

**Screenshots**
<img width="1043" alt="Screenshot 2023-04-14 at 13 53 47" src="https://user-images.githubusercontent.com/5786734/231953222-c17cd966-af9c-407f-95f3-385fe2bb911e.png">

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 6.2.10-arch1-1

**Smartphone (please complete the following information):**
Not applicable.

**Additional context**
None.

**Comment by dsilhavy** [comment]
@WingPig99 Try the development branch please, the error should be fixed there. @davidjwbbc  addressed this here https://github.com/5G-MAG/rt-5gms-application-server/pull/63

**Comment by davidjwbbc** [comment]
Copied from Slack:

> Release Candidate for v1.1.1 is now available ([rt-5gms-application-server-1.1.1-rc1](https://github.com/5G-MAG/rt-5gms-application-server/tree/rt-5gms-application-server-1.1.1-rc1) tag).
> 
> This is a bug fix release to deal with a change to the Python fastapi module. The recent change to fastapi now forbids the setting of a default value for a URL path variable (even None is not allowed), however the default openapi-generator python-fastapi templates add a None default value in the call to the Path() function. This fix simply modifies the template to exclude the default value for URL path variables in the generated code.
> 
> Other that the fix for fastapi detailed above, the rest of the 5GMS Application Server works exactly the same as v1.1.0.
> 
> Please checkout and test this new version by using the git clone command:
> ```
> git clone --recurse-submodules -b rt-5gms-application-server-1.1.1-rc1 https://github.com/5G-MAG/rt-5gms-application-server.git
> ```
> 
> Please raise any issues found in [the rt-5gms-application-server repository issues](https://github.com/5G-MAG/rt-5gms-application-server/issues).
> 
> If there are no major issues with this release candidate reported by next Friday I'll do a formal release of v1.1.1.

This new release candidate should fix your issues. I'll close this ticket upon formal release of v1.1.1.

**Comment by WingPig99** [comment]
Thanks a lot. Now, everything works fine.
