### ISSUE TITLE
Upstream redirects are passed to client

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/rt-5gms-application-server#70]
# Description
When the AS receives an HTTP redirect from an upstream origin server it is incorrectly passed on to the UE rather than being processed by the AS. If this happens on the manifest, this effectively diverts the UE away from the AS for playback of the media. This means that control over network slicing and network policies may be bypassed (UE registers policy against the AS connection at the start of the session).

# Reproducing
1. Configure the AF with an upstream ingest server that sends redirects on manifest request.
2. Check the result of requesting a manifest via the interface at M4d, it will contain a 3XX response redirecting the client away from the AS.

# Expected behaviour
Media streaming session at M4d remains served via the AS.

# Suggested behaviour
The AS should intercept the redirects and set up a path through the same provisioning session prefix path for M4d. The AS can then issue the redirect to the entity in the new M4d path.

# Additional context
Observed on the BBC 5G testbed when using a ingest CDN that redirects requests.

**Comment by davidjwbbc** [comment]
This is not going to be easy as it will require dynamic programming of proxy URLs in the AS when it sees a redirect response to a upstream request.

My initial suggestion would be to build a table mapping a UUID to seen redirection URL prefixes (redirection URL minus the final path element). Then it could map requests for {m4d-prefix}/{redirect-uuid}/object to the new redirected URL.

I'm not sure how much of this is possible with lua inside nginx, but it will be a marked degree of extra complexity.

**Comment by davidjwbbc** [comment]
@rjb1000 what are your thoughts on this issue?

**Comment by rjb1000** [comment]
> @rjb1000 what are your thoughts on this issue?

Could the AS to follow the redirect itself and make it sticky?

**Comment by davidjwbbc** [comment]
Not really because the client then uses the manifest URL as a base to request media segments and how do you then know if a media segment request is for that manifest or another one and therefore how to redirect it. I think the only way would be to rewrite the redirect Location in such a way that a request to that, or any relative resource locator, contains a unique identifier that allows tracing back to the original redirect.

**Comment by dsilhavy** [comment]
Nor sure if this helps but note that for DASH you can use `Location` and `BaseURL` elements in the manifest. `Location` points to the location of the manifest while `BaseURL` is used for segment requests.

**Comment by rjb1000** [comment]
> Nor sure if this helps but note that for DASH you can use `Location` and `BaseURL` elements in the manifest. `Location` points to the location of the manifest while `BaseURL` is used for segment requests.

Manifest manipulation is still available as a last resort. But I think @davidjwbbc is keen to find a protocol-based solution if at all possible, to avoid having to resort to that.

**Comment by davidjwbbc** [comment]
Raised 5G-MAG/Standards#69 for SA4 discussion of this issue.

**Comment by davidjwbbc** [comment]
Demonstrated dynamic redirect learning working under test environment, will now deploy and run some more tests in a more representative environment (i.e. full AF & AS deployment with multiple provisioning sessions).
