### ISSUE TITLE
CI/CD - Automated deployment to Linode instance

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-5gms-application-server#76]
# Feature description
5G-MAG provides a Linode instance to host the Application Server (AS). This enables 5GMS Client components to talk against the provided interface M4 without setting up the AS on a dedicated machine.

The deployment of the latest version of the AS should be integrated into a CI/CD workflow. That way it is always available on the Linode instance without requiring a manual update and installation. 

As a first step, the build process for the AS should be performed in the Github cluster for each new pull request and once code is added to the development branch.

**Comment by dsilhavy** [comment]
@RaghuMeda Can't assign this to you for some reason, can you comment here? Might work then.

**Comment by rjb1000** [comment]
@dsilhavy: Looks like you already created #59, a few months back, so this issue is a duplicate of that.

**Comment by dsilhavy** [comment]
My bad, thanks for the hint @rjb1000
