### ISSUE TITLE
Development branch: Missing Nginx mime.types after clean installation

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-5gms-application-server#83]
## Description
I am doing a clean installation of the Application Server on a freshy installed Ubuntu 22 machine using the current `development` branch. Latest commit: https://github.com/5G-MAG/rt-5gms-application-server/commit/4ebaa7b10a40a2e0bc37159916ced366a3e0c7a5

I ran into an issue with missing nginx mime.types when starting the Application Server with `sudo 5gms-application-server `

The following error occured:

````
ERROR:NginxWebProxy:nginx: [emerg] open() "/etc/nginx/mime.types" failed (2: No such file or directory) in /tmp/rt_5gms_as.conf:53

INFO:rt-5gms-as:Web proxy process exited, has been restarted
````

I did not have a previous version of nginx installed and only installed openresty (which includes nginx).

## Solution
The solution is to include the `mime.types` located in the nginx installation of openresty. For that reason we need to adjust `nginx.conf.tmpl` prior to the installation of the Application Server:

````
include             /usr/local/openresty/nginx/conf/mime.types;
````

**Comment by davidjwbbc** [comment]
I think the AS python should check which mime.types file is available and use a variable to set that path in the `nginx.conf.tmpl`.
